KEY_MAPPING = {'vehicle_id': {'autoscout24': 'id', 'mobile': 'id', 'otomoto': 'vehicle_id', 'marktplaats': 'id'},
               'listing_url': {'autoscout24': 'url', 'mobile': 'url', 'otomoto': 'url', 'marktplaats': 'url'},
               'title': {'autoscout24': 'title', 'mobile': 'title', 'otomoto': 'title', 'marktplaats': 'title'},
               'subtitle': {'autoscout24': 'vehicle_subtitle', 'mobile': None, 'otomoto': 'shortDescription',
                            'marktplaats': None},
               'price': {'autoscout24': 'price', 'mobile': 'price', 'otomoto': 'price', 'marktplaats': 'price'},
               'price_info': {'autoscout24': 'price_text', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'price_label': {'autoscout24': 'tracking_priceLabel', 'mobile': None, 'otomoto': None,
                               'marktplaats': None},
               'make': {'autoscout24': 'vehicle_make', 'mobile': 'vehicle_make', 'otomoto': 'make',
                        'marktplaats': 'brand'},
               'model': {'autoscout24': 'vehicle_model', 'mobile': 'vehicle_model', 'otomoto': 'model',
                         'marktplaats': 'model'},
               'model_version': {'autoscout24': 'vehicle_modelVersionInput', 'mobile': 'vehicle_modelVersionInput',
                                 'otomoto': 'version_label', 'marktplaats': None},
               'model_range': {'autoscout24': None, 'mobile': 'modelRange', 'otomoto': None, 'marktplaats': None},
               'trim_line': {'autoscout24': None, 'mobile': 'trimLine', 'otomoto': None, 'marktplaats': 'trim'},
               'vehicle_type': {'autoscout24': 'vehicle_articleType', 'mobile': 'vc', 'otomoto': None,
                                'marktplaats': 'vehicleType'},
               'category': {'autoscout24': None, 'mobile': 'category', 'otomoto': None, 'marktplaats': None},
               'body_type': {'autoscout24': 'bodyType', 'mobile': None, 'otomoto': 'body_type', 'marktplaats': None},
               'make_id': {'autoscout24': 'makeId', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'model_id': {'autoscout24': 'modelId', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'model_generation_id': {'autoscout24': 'modelGenerationId', 'mobile': None, 'otomoto': 'generation',
                                       'marktplaats': None},
               'model_variant_id': {'autoscout24': 'modelVariantId', 'mobile': None, 'otomoto': None,
                                    'marktplaats': None},
               'motor_type_id': {'autoscout24': 'motorTypeId', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'trim_line_id': {'autoscout24': 'trimLineId', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'sku': {'autoscout24': None, 'mobile': 'sku', 'otomoto': None, 'marktplaats': None},
               'hsn_tsn': {'autoscout24': 'hsnTsn', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'identifier': {'autoscout24': 'identifier', 'mobile': None, 'otomoto': 'vin', 'marktplaats': None},
               'power_kw': {'autoscout24': 'rawPowerInKw', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'power_hp': {'autoscout24': 'rawPowerInHp', 'mobile': None, 'otomoto': 'engine_power',
                            'marktplaats': 'powerInHorsePower'},
               'power_display': {'autoscout24': 'vehicle_detail_power', 'mobile': 'Power (HP)', 'otomoto': None,
                                 'marktplaats': None},
               'power_kw_display': {'autoscout24': 'powerInKw', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'power_hp_display': {'autoscout24': 'powerInHp', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'displacement_ccm': {'autoscout24': 'rawDisplacementInCCM', 'mobile': None, 'otomoto': 'engine_capacity',
                                    'marktplaats': 'cylinderCapacity'},
               'displacement_display': {'autoscout24': 'displacementInCCM', 'mobile': 'Displacement', 'otomoto': None,
                                        'marktplaats': None},
               'cylinders': {'autoscout24': 'cylinders', 'mobile': 'cylinder', 'otomoto': None,
                             'marktplaats': 'numberOfCylinders'},
               'gears': {'autoscout24': 'gears', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'weight': {'autoscout24': 'weight', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'net_weight': {'autoscout24': None, 'mobile': 'netWeight', 'otomoto': None,
                              'marktplaats': 'emptyWeight'},
               'fuel_type': {'autoscout24': 'vehicle_fuel', 'mobile': 'Fuel Type', 'otomoto': 'fuel_type',
                             'marktplaats': 'fuel'},
               'fuel_category': {'autoscout24': 'fuelCategory', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'primary_fuel': {'autoscout24': 'primaryFuel', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'transmission': {'autoscout24': 'vehicle_transmission', 'mobile': 'Transmission Type',
                                'otomoto': 'gearbox', 'marktplaats': 'transmission'},
               'air_conditioning_type': {'autoscout24': None, 'mobile': 'climatisation',
                                         'otomoto': 'air_conditioning_type', 'marktplaats': None},
               'transmission_type': {'autoscout24': 'transmissionType', 'mobile': None, 'otomoto': None,
                                     'marktplaats': None},
               'drive_train': {'autoscout24': 'driveTrain', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'has_particle_filter': {'autoscout24': 'hasParticleFilter', 'mobile': None, 'otomoto': None,
                                       'marktplaats': None},
               'particle_filter': {'autoscout24': None, 'mobile': 'Partikelfilter', 'otomoto': 'particle_filter',
                                   'marktplaats': None},
               'fuel_consumption_combined': {'autoscout24': 'fuelConsumptionCombined', 'mobile': None,
                                             'otomoto': 'combined_consumption', 'marktplaats': 'fuelConsumption'},
               'fuel_consumption_urban': {'autoscout24': 'fuelConsumptionUrban', 'mobile': None,
                                          'otomoto': 'urban_consumption', 'marktplaats': None},
               'fuel_consumption_extra_urban': {'autoscout24': 'fuelConsumptionExtraUrban', 'mobile': None,
                                                'otomoto': 'extra_urban_consumption', 'marktplaats': None},
               'co2_emission': {'autoscout24': 'vehicle_detail_co2_emission', 'mobile': 'CO2 in g per km',
                                'otomoto': 'co2_emissions', 'marktplaats': 'co2emission'},
               'co2_emission_combined': {'autoscout24': 'co2emissionInGramPerKmWithFallback', 'mobile': None,
                                         'otomoto': None, 'marktplaats': None},
               'co2_emissions_combined_fallback': {'autoscout24': 'co2EmissionsCombinedWithFallback', 'mobile': None,
                                                   'otomoto': None, 'marktplaats': None},
               'co2_emissions_combined_weighted': {'autoscout24': 'co2EmissionsCombinedWeightedWithFallback',
                                                   'mobile': None, 'otomoto': None, 'marktplaats': None},
               'co2_emissions_discharged': {'autoscout24': 'co2EmissionsDischarged', 'mobile': None, 'otomoto': None,
                                            'marktplaats': None},
               'co2_class': {'autoscout24': 'co2ClassWithFallback', 'mobile': 'EU CO2 Class', 'otomoto': None,
                             'marktplaats': None},
               'co2_class_discharged': {'autoscout24': 'co2ClassDischarged', 'mobile': None, 'otomoto': None,
                                        'marktplaats': None},
               'emission_sticker': {'autoscout24': None, 'mobile': 'emissionsSticker', 'otomoto': None,
                                    'marktplaats': None},
               'emission_standard': {'autoscout24': None, 'mobile': 'attr_emc', 'otomoto': None, 'marktplaats': None},
               'consumption_combined': {'autoscout24': 'consumptionCombinedWithFallback', 'mobile': None,
                                        'otomoto': None, 'marktplaats': None},
               'consumption_combined_weighted': {'autoscout24': 'consumptionCombinedWeightedWithFallback',
                                                 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'consumption_combined_discharged': {'autoscout24': 'consumptionCombinedDischarged', 'mobile': None,
                                                   'otomoto': None, 'marktplaats': None},
               'consumption_electric_combined': {'autoscout24': 'consumptionElectricCombinedWithFallback',
                                                 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'consumption_electric_combined_weighted': {
                   'autoscout24': 'consumptionElectricCombinedWeightedWithFallback', 'mobile': None, 'otomoto': None,
                   'marktplaats': None},
               'consumption_city': {'autoscout24': 'consumptionCity', 'mobile': None, 'otomoto': None,
                                    'marktplaats': None},
               'consumption_city_discharged': {'autoscout24': 'consumptionCityDischarged', 'mobile': None,
                                               'otomoto': None, 'marktplaats': None},
               'consumption_suburban': {'autoscout24': 'consumptionSuburban', 'mobile': None, 'otomoto': None,
                                        'marktplaats': None},
               'consumption_suburban_discharged': {'autoscout24': 'consumptionSuburbanDischarged', 'mobile': None,
                                                   'otomoto': None, 'marktplaats': None},
               'consumption_rural': {'autoscout24': 'consumptionRural', 'mobile': None, 'otomoto': None,
                                     'marktplaats': None},
               'consumption_rural_discharged': {'autoscout24': 'consumptionRuralDischarged', 'mobile': None,
                                                'otomoto': None, 'marktplaats': None},
               'consumption_highway': {'autoscout24': 'consumptionHighway', 'mobile': None, 'otomoto': None,
                                       'marktplaats': None},
               'consumption_highway_discharged': {'autoscout24': 'consumptionHighwayDischarged', 'mobile': None,
                                                  'otomoto': None, 'marktplaats': None},
               'consumption_electric_city': {'autoscout24': 'consumptionElectricCity', 'mobile': None, 'otomoto': None,
                                             'marktplaats': None},
               'consumption_electric_suburban': {'autoscout24': 'consumptionElectricSuburban', 'mobile': None,
                                                 'otomoto': None, 'marktplaats': None},
               'consumption_electric_rural': {'autoscout24': 'consumptionElectricRural', 'mobile': None,
                                              'otomoto': None, 'marktplaats': None},
               'consumption_electric_highway': {'autoscout24': 'consumptionElectricHighway', 'mobile': None,
                                                'otomoto': None, 'marktplaats': None},
               'environment_pkw_envkv': {'autoscout24': 'environmentPkwEnVKV', 'mobile': None, 'otomoto': None,
                                         'marktplaats': None},
               'environment_eu_directive': {'autoscout24': 'environmentEuDirective', 'mobile': None, 'otomoto': None,
                                            'marktplaats': None},
               'environment_bimschv35': {'autoscout24': 'environmentBImSchV35', 'mobile': None, 'otomoto': None,
                                         'marktplaats': None},
               'wltp': {'autoscout24': 'wltp', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'energy_consumption': {'autoscout24': None, 'mobile': 'envkv.energyConsumption', 'otomoto': None,
                                      'marktplaats': None},
               'consumption_costs': {'autoscout24': 'consumptionCosts', 'mobile': 'envkv.consumptionCosts',
                                     'otomoto': None, 'marktplaats': None},
               'consumption_costs_year': {'autoscout24': 'consumptionCostsYear', 'mobile': None, 'otomoto': None,
                                          'marktplaats': None},
               'fuel_price': {'autoscout24': 'fuelPrice', 'mobile': 'envkv.fuel.price', 'otomoto': None,
                              'marktplaats': None},
               'co2_costs': {'autoscout24': None, 'mobile': 'envkv.co2Costs', 'otomoto': None, 'marktplaats': None},
               'co2_costs_average': {'autoscout24': 'co2CostsAverage', 'mobile': None, 'otomoto': None,
                                     'marktplaats': None},
               'co2_costs_high': {'autoscout24': 'co2CostsHigh', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'co2_costs_low': {'autoscout24': 'co2CostsLow', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'vehicle_tax': {'autoscout24': 'vehicleTax', 'mobile': 'envkv.tax', 'otomoto': None,
                               'marktplaats': 'roadTax'},
               'engine_type': {'autoscout24': None, 'mobile': 'envkv.engineType', 'otomoto': None, 'marktplaats': None},
               'other_energy_source': {'autoscout24': None, 'mobile': 'envkv.otherEnergySource', 'otomoto': None,
                                       'marktplaats': None},
               'mileage_km': {'autoscout24': 'mileageInKmRaw', 'mobile': None, 'otomoto': 'mileage',
                              'marktplaats': 'mileage'},
               'mileage_display': {'autoscout24': 'vehicle_mileageInKm', 'mobile': 'Milage', 'otomoto': None,
                                   'marktplaats': None},
               'mileage_detail': {'autoscout24': 'vehicle_detail_mileage', 'mobile': None, 'otomoto': None,
                                  'marktplaats': None},
               'mileage_in_km': {'autoscout24': 'mileageInKm', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'first_registration': {'autoscout24': 'vehicle_detail_first_registration',
                                      'mobile': 'First Registration', 'otomoto': 'date_registration',
                                      'marktplaats': None},
               'first_registration_raw': {'autoscout24': 'firstRegistrationDateRaw', 'mobile': None, 'otomoto': None,
                                          'marktplaats': None},
               'first_registration_date': {'autoscout24': 'firstRegistrationDate', 'mobile': None, 'otomoto': None,
                                           'marktplaats': None},
               'production_year': {'autoscout24': 'productionYear', 'mobile': None, 'otomoto': 'year',
                                   'marktplaats': None},
               'construction_year': {'autoscout24': None, 'mobile': 'constructionYear', 'otomoto': None,
                                     'marktplaats': 'constructionYear'},
               'last_inspection': {'autoscout24': None, 'mobile': 'Last inspection', 'otomoto': None,
                                   'marktplaats': None},
               'next_inspection': {'autoscout24': 'nextVehicleSafetyInspection', 'mobile': None, 'otomoto': None,
                                   'marktplaats': None},
               'new_inspection': {'autoscout24': 'newInspection', 'mobile': 'Inspektion neu', 'otomoto': None,
                                  'marktplaats': None},
               'last_service_date': {'autoscout24': 'lastTechnicalServiceDate', 'mobile': 'lastMaintenanceDate',
                                     'otomoto': None, 'marktplaats': None},
               'last_service_mileage': {'autoscout24': None, 'mobile': 'lastMaintenanceMileage', 'otomoto': None,
                                        'marktplaats': None},
               'last_belt_service': {'autoscout24': 'lastBeltServiceDate', 'mobile': None, 'otomoto': None,
                                     'marktplaats': None},
               'full_service_history': {'autoscout24': 'hasFullServiceHistory', 'mobile': None,
                                        'otomoto': 'service_record', 'marktplaats': 'serviceHistory'},
               'service_book_maintained': {'autoscout24': None, 'mobile': 'Scheckheftgepflegt', 'otomoto': None,
                                           'marktplaats': None},
               'offer_type': {'autoscout24': 'vehicle_offerType', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'condition': {'autoscout24': None, 'mobile': 'damageCondition', 'otomoto': 'new_used',
                             'marktplaats': 'condition'},
               'damage_condition': {'autoscout24': None, 'mobile': 'attr_subc', 'otomoto': 'damaged',
                                    'marktplaats': None},
               'had_accident': {'autoscout24': 'hadAccident', 'mobile': None, 'otomoto': 'no_accident',
                                'marktplaats': None},
               'previous_owners': {'autoscout24': 'noOfPreviousOwners', 'mobile': 'attr_pvo',
                                   'otomoto': 'original_owner', 'marktplaats': 'totalNumberOfOwners'},
               'is_rental': {'autoscout24': 'isRental', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'non_smoking': {'autoscout24': 'nonSmoking', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'non_smoking_vehicle': {'autoscout24': None, 'mobile': 'Nichtraucher-Fahrzeug', 'otomoto': None,
                                       'marktplaats': None},
               'has_registration': {'autoscout24': 'hasCarRegistration', 'mobile': None, 'otomoto': 'registered',
                                    'marktplaats': None},
               'new_driver_suitable': {'autoscout24': 'newDriverSuitable', 'mobile': None, 'otomoto': None,
                                       'marktplaats': None},
               'country_version': {'autoscout24': None, 'mobile': 'Country version', 'otomoto': 'country_origin',
                                   'marktplaats': None},
               'original_market': {'autoscout24': 'originalMarket', 'mobile': None, 'otomoto': None,
                                   'marktplaats': None},
               'type': {'autoscout24': 'type', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'seats': {'autoscout24': 'numberOfSeats', 'mobile': '# of Seats', 'otomoto': 'nr_seats',
                         'marktplaats': 'numberOfSeats'},
               'doors': {'autoscout24': 'numberOfDoors', 'mobile': '# of doors', 'otomoto': 'door_count',
                         'marktplaats': 'numberOfDoors'},
               'color': {'autoscout24': 'bodyColor', 'mobile': 'Exterior Color', 'otomoto': 'color',
                         'marktplaats': 'color'},
               'color_original': {'autoscout24': 'bodyColorOriginal', 'mobile': None, 'otomoto': None,
                                  'marktplaats': None},
               'manufacturer_color': {'autoscout24': None, 'mobile': 'manufacturerColorName', 'otomoto': None,
                                      'marktplaats': None},
               'paint_type': {'autoscout24': 'paintType', 'mobile': None, 'otomoto': 'colour_type',
                              'marktplaats': None},
               'upholstery': {'autoscout24': 'upholstery', 'mobile': None, 'otomoto': 'upholstery_type',
                              'marktplaats': 'upholstery'},
               'upholstery_color': {'autoscout24': 'upholsteryColor', 'mobile': None, 'otomoto': None,
                                    'marktplaats': None},
               'interior': {'autoscout24': None, 'mobile': 'interior', 'otomoto': None, 'marktplaats': None},
               'interior_color': {'autoscout24': None, 'mobile': 'interior_color', 'otomoto': None,
                                  'marktplaats': 'interiorColor'},
               'interior_type': {'autoscout24': None, 'mobile': 'interior_type', 'otomoto': None, 'marktplaats': None},
               'vehicle_model_id': {'autoscout24': 'vehicle_modelId', 'mobile': None, 'otomoto': None,
                                    'marktplaats': None},
               'vehicle_transmission': {'autoscout24': 'vehicle_detail_transmission', 'mobile': None, 'otomoto': None,
                                        'marktplaats': None},
               'vehicle_fuel_type': {'autoscout24': 'vehicle_detail_fuel', 'mobile': None, 'otomoto': None,
                                     'marktplaats': None},
               'vehicle_fuel_consumption': {'autoscout24': 'vehicle_detail_fuel_consumption', 'mobile': None,
                                            'otomoto': None, 'marktplaats': None},
               'model_or_line_id': {'autoscout24': 'modelOrModelLineId', 'mobile': None, 'otomoto': None,
                                    'marktplaats': None},
               'wheel_base': {'autoscout24': 'wheelBase', 'mobile': None, 'otomoto': None, 'marktplaats': 'wheelBase'},
               'total_height': {'autoscout24': 'totalHeight', 'mobile': None, 'otomoto': None,
                                'marktplaats': 'heightInMeters'},
               'total_width': {'autoscout24': 'totalWidth', 'mobile': None, 'otomoto': None,
                               'marktplaats': 'widthInMeters'},
               'total_length': {'autoscout24': 'totalLength', 'mobile': None, 'otomoto': None,
                                'marktplaats': 'lengthInMeters'},
               'gross_vehicle_weight': {'autoscout24': 'grossVehicleWeight', 'mobile': None, 'otomoto': None,
                                        'marktplaats': 'maxAllowedWeight'},
               'gross_vehicle_weight_detail': {'autoscout24': 'vehicle_detail_zul._gesamtgewicht', 'mobile': None,
                                               'otomoto': None, 'marktplaats': None},
               'payload': {'autoscout24': 'payload', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'load_width': {'autoscout24': 'loadWidth', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'load_height': {'autoscout24': 'loadHeight', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'load_length': {'autoscout24': 'loadLength', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'load_volume': {'autoscout24': 'loadVolume', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'trailer_load_braked': {'autoscout24': None, 'mobile': 'trailerLoadBraked', 'otomoto': None,
                                       'marktplaats': 'maxWeightWithBrakes'},
               'trailer_load_unbraked': {'autoscout24': None, 'mobile': 'trailerLoadUnbraked', 'otomoto': None,
                                         'marktplaats': 'maxWeightWithoutBrakes'},
               'max_towing_weight': {'autoscout24': 'maximumTowingWeight', 'mobile': None, 'otomoto': None,
                                     'marktplaats': None},
               'max_nose_weight': {'autoscout24': None, 'mobile': 'maxNoseWeight', 'otomoto': None,
                                   'marktplaats': None},
               'fuel_tank_volume': {'autoscout24': None, 'mobile': 'fuelTankVolume', 'otomoto': None,
                                    'marktplaats': 'fuelTankCapacity'},
               'battery_ownership': {'autoscout24': 'batteryOwnershipType', 'mobile': None,
                                     'otomoto': 'battery_ownership_model', 'marktplaats': None},
               'battery_charging_time': {'autoscout24': 'batteryChargingTime', 'mobile': None, 'otomoto': None,
                                         'marktplaats': 'batteryChargeTime'},
               'battery_capacity': {'autoscout24': None, 'mobile': 'batteryCapacity', 'otomoto': 'battery_capacity',
                                    'marktplaats': 'batteryCapacity'},
               'battery_certificate': {'autoscout24': 'Batteriezertifikat', 'mobile': 'Batteriezertifikat',
                                       'otomoto': None, 'marktplaats': None},
               'battery': {'autoscout24': None, 'mobile': 'battery', 'otomoto': None, 'marktplaats': None},
               'electric_range': {'autoscout24': 'electricRangeWithFallback', 'mobile': None, 'otomoto': 'autonomy',
                                  'marktplaats': 'range'},
               'electric_range_city': {'autoscout24': 'electricRangeCity', 'mobile': None, 'otomoto': None,
                                       'marktplaats': None},
               'number_of_beds': {'autoscout24': 'numberOfBeds', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'number_of_axles': {'autoscout24': 'numberOfAxles', 'mobile': None, 'otomoto': None,
                                   'marktplaats': None},
               'vehicle_art': {'autoscout24': 'vehicle_detail_fahrzeugart', 'mobile': 'vehicle_detail_fahrzeugart',
                               'otomoto': None, 'marktplaats': None},
               'double_cab': {'autoscout24': 'Doppelkabine', 'mobile': 'Doppelkabine', 'otomoto': None,
                              'marktplaats': None},
               'awning': {'autoscout24': 'Markise', 'mobile': 'Markise', 'otomoto': None, 'marktplaats': None},
               'sliding_door_type': {'autoscout24': None, 'mobile': 'slidingDoor', 'otomoto': None,
                                     'marktplaats': None},
               'sliding_door': {'autoscout24': 'Schiebetür', 'mobile': None, 'otomoto': None,
                                'marktplaats': 'Schuifdeur'},
               'sliding_door_right': {'autoscout24': 'Schiebetür rechts', 'mobile': None, 'otomoto': None,
                                      'marktplaats': None},
               'sliding_door_left': {'autoscout24': 'Schiebetür links', 'mobile': None, 'otomoto': None,
                                     'marktplaats': None},
               'country_code': {'autoscout24': 'location_countryCode', 'mobile': 'Country Code', 'otomoto': None,
                                'marktplaats': None},
               'postal_code': {'autoscout24': 'location_zip', 'mobile': 'Postal Code', 'otomoto': None,
                               'marktplaats': None},
               'city': {'autoscout24': 'location_city', 'mobile': 'City', 'otomoto': None, 'marktplaats': None},
               'street': {'autoscout24': 'location_street', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'seller_name': {'autoscout24': 'seller_name', 'mobile': 'seller_name', 'otomoto': 'seller_name',
                               'marktplaats': 'seller_name'},
               'license_plate': {'autoscout24': 'licensePlate', 'mobile': None, 'otomoto': None,
                                 'marktplaats': 'licensePlate'},
               'images': {'autoscout24': 'images', 'mobile': 'images', 'otomoto': 'images', 'marktplaats': 'images'},
               'description': {'autoscout24': 'description', 'mobile': 'description', 'otomoto': 'description',
                               'marktplaats': 'description'},
               'carpass_mileage_url': {'autoscout24': 'carpassMileageUrl', 'mobile': None, 'otomoto': None,
                                       'marktplaats': 'carPassUrl'},
               'tracking_first_registration': {'autoscout24': 'tracking_firstRegistration', 'mobile': None,
                                               'otomoto': None, 'marktplaats': None},
               'tracking_fuel_type': {'autoscout24': 'tracking_fuelType', 'mobile': None, 'otomoto': None,
                                      'marktplaats': None},
               'tracking_image_content': {'autoscout24': 'tracking_imageContent', 'mobile': None, 'otomoto': None,
                                          'marktplaats': None},
               'tracking_smyle_eligible': {'autoscout24': 'tracking_isSmyleEligible', 'mobile': None, 'otomoto': None,
                                           'marktplaats': None},
               'tracking_mileage': {'autoscout24': 'tracking_mileage', 'mobile': None, 'otomoto': None,
                                    'marktplaats': None},
               'tracking_price': {'autoscout24': 'tracking_price', 'mobile': None, 'otomoto': None,
                                  'marktplaats': None},
               'tracking_model_taxonomy': {'autoscout24': 'tracking_modelTaxonomy', 'mobile': None, 'otomoto': None,
                                           'marktplaats': None},
               'tracking_boosting_product': {'autoscout24': 'tracking_boosting_product', 'mobile': None,
                                             'otomoto': None, 'marktplaats': None},
               'tracking_relevance_adjustment': {'autoscout24': 'tracking_relevance_adjustment', 'mobile': None,
                                                 'otomoto': None, 'marktplaats': None},
               'tracking_boost_level': {'autoscout24': 'tracking_boost_level', 'mobile': None, 'otomoto': None,
                                        'marktplaats': None},
               'tracking_applied_boost_level': {'autoscout24': 'tracking_applied_boost_level', 'mobile': None,
                                                'otomoto': None, 'marktplaats': None},
               'tracking_order_bucket': {'autoscout24': 'tracking_orderBucket', 'mobile': None, 'otomoto': None,
                                         'marktplaats': None},
               'tracking_topspot_algorithm': {'autoscout24': 'tracking_topspot_algorithm', 'mobile': None,
                                              'otomoto': None, 'marktplaats': None},
               'tracking_topspot_dealer_id': {'autoscout24': 'tracking_topspot_dealer_id', 'mobile': None,
                                              'otomoto': None, 'marktplaats': None},
               'attr_c': {'autoscout24': None, 'mobile': 'attr_c', 'otomoto': None, 'marktplaats': None},
               'attr_con': {'autoscout24': None, 'mobile': 'attr_con', 'otomoto': None, 'marktplaats': None},
               'attr_nw': {'autoscout24': None, 'mobile': 'attr_nw', 'otomoto': None, 'marktplaats': None},
               'attr_bc': {'autoscout24': None, 'mobile': 'attr_bc', 'otomoto': None, 'marktplaats': None},
               'attr_yc': {'autoscout24': None, 'mobile': 'attr_yc', 'otomoto': None, 'marktplaats': None},
               'abs': {'autoscout24': 'ABS', 'mobile': 'ABS', 'otomoto': 'antilock_brake_system', 'marktplaats': 'ABS'},
               'esp': {'autoscout24': 'ESP', 'mobile': 'ESP', 'otomoto': 'esp',
                       'marktplaats': 'Electronic Stability Program (ESP)'},
               'traction_control': {'autoscout24': 'Traktionskontrolle', 'mobile': 'Traktionskontrolle',
                                    'otomoto': 'traction_control', 'marktplaats': 'Traction-control'},
               'driver_airbag': {'autoscout24': 'Fahrerairbag', 'mobile': None, 'otomoto': 'driver_airbag',
                                 'marktplaats': None},
               'passenger_airbag': {'autoscout24': 'Beifahrerairbag', 'mobile': None, 'otomoto': 'passenger_airbag',
                                    'marktplaats': None}, 'side_airbag': {'autoscout24': 'Seitenairbag', 'mobile': None,
                                                                          'otomoto': 'side_airbag_driver_and_passenger',
                                                                          'marktplaats': None},
               'head_airbag': {'autoscout24': 'Kopfairbag', 'mobile': None, 'otomoto': 'head_airbags_front',
                               'marktplaats': None},
               'rear_airbag': {'autoscout24': 'Airbag hinten', 'mobile': None, 'otomoto': 'side_airbags_rear',
                               'marktplaats': None},
               'airbag': {'autoscout24': None, 'mobile': 'airbag', 'otomoto': None, 'marktplaats': 'Airbags'},
               'immobilizer': {'autoscout24': 'Wegfahrsperre', 'mobile': 'Elektr. Wegfahrsperre', 'otomoto': None,
                               'marktplaats': 'Startonderbreker'},
               'emergency_brake_assist': {'autoscout24': 'Notbremsassistent', 'mobile': 'Notbremsassistent',
                                          'otomoto': 'brake_assist', 'marktplaats': 'Emergency brake assist'},
               'blind_spot_assist': {'autoscout24': 'Totwinkel-Assistent', 'mobile': 'Totwinkel-Assistent',
                                     'otomoto': 'blind_spot_warning', 'marktplaats': 'Dodehoekdetectie'},
               'lane_assist': {'autoscout24': 'Spurhalteassistent', 'mobile': 'Spurhalteassistent',
                               'otomoto': 'lane_control_assistant', 'marktplaats': 'Lane Departure Warning'},
               'distance_warning': {'autoscout24': 'Abstandswarner', 'mobile': 'Abstandswarner',
                                    'otomoto': 'distance_control', 'marktplaats': None},
               'traffic_sign_recognition': {'autoscout24': 'Verkehrszeichenerkennung',
                                            'mobile': 'Verkehrszeichenerkennung',
                                            'otomoto': 'active_speed_sign_recognition',
                                            'marktplaats': 'Verkeersbordherkenning'},
               'luggage_partition': {'autoscout24': 'Gepäckraumabtrennung', 'mobile': None, 'otomoto': None,
                                     'marktplaats': None},
               'folding_rear_seat': {'autoscout24': 'teilb. Rücksitzbank', 'mobile': None, 'otomoto': None,
                                     'marktplaats': None},
               'lumbar_support': {'autoscout24': 'Lordosenstütze', 'mobile': None,
                                  'otomoto': 'lumbar_adjust_driver_electric', 'marktplaats': None},
               'tow_bar': {'autoscout24': 'Anhängerkupplung', 'mobile': None, 'otomoto': 'towbar',
                           'marktplaats': 'Trekhaak'},
               'wireless_phone_charging': {'autoscout24': 'Induktionsladen für Smartphones', 'mobile': None,
                                           'otomoto': 'wireless_device_charging', 'marktplaats': None},
               'keyless_central_locking': {'autoscout24': 'Schlüssellose Zentralverriegelung', 'mobile': None,
                                           'otomoto': None, 'marktplaats': None},
               'seat_ventilation': {'autoscout24': 'Sitzbelüftung', 'mobile': None, 'otomoto': 'ventilated_front_seat',
                                    'marktplaats': 'Stoelventilatie'},
               'vehicle_co2_class': {'autoscout24': 'vehicle_detail_co₂-klasse', 'mobile': None, 'otomoto': None,
                                     'marktplaats': None},
               'wind_deflector_for_convertible': {'autoscout24': 'Windschott(für Cabrio)', 'mobile': None,
                                                  'otomoto': None, 'marktplaats': None},
               'hill_start_assist': {'autoscout24': 'Berganfahrassistent', 'mobile': 'Berganfahrassistent',
                                     'otomoto': 'hill_holder', 'marktplaats': None},
               'alarm_system': {'autoscout24': 'Alarmanlage', 'mobile': 'Alarmanlage', 'otomoto': None,
                                'marktplaats': 'Alarm'},
               'isofix': {'autoscout24': 'Isofix', 'mobile': 'Isofix', 'otomoto': 'child_seat_fixation',
                          'marktplaats': 'Isofix'},
               'isofix_passenger': {'autoscout24': None, 'mobile': 'Isofix Beifahrersitz', 'otomoto': None,
                                    'marktplaats': None},
               'tire_pressure_monitoring': {'autoscout24': 'Reifendruckkontrollsystem',
                                            'mobile': 'Reifendruckkontrolle', 'otomoto': 'tyre_pressure_control',
                                            'marktplaats': None},
               'emergency_call': {'autoscout24': 'Notrufsystem', 'mobile': 'Notrufsystem',
                                  'otomoto': 'automatic_emergency_call', 'marktplaats': None},
               'night_vision': {'autoscout24': 'Nachtsicht-Assistent', 'mobile': 'Nachtsicht-Assistent',
                                'otomoto': None, 'marktplaats': None},
               'self_steering_park_assist': {'autoscout24': 'Einparkhilfe selbstlenkendes System',
                                             'mobile': 'Einparkhilfe selbstlenkendes System',
                                             'otomoto': 'autonomous_parking_system', 'marktplaats': None},
               'power_steering': {'autoscout24': 'Servolenkung', 'mobile': 'Servolenkung', 'otomoto': 'power_steering',
                                  'marktplaats': None},
               'central_locking': {'autoscout24': 'Zentralverriegelung', 'mobile': 'Zentralverriegelung',
                                   'otomoto': None, 'marktplaats': 'Centrale vergrendeling'},
               'central_locking_remote': {'autoscout24': 'Zentralverriegelung mit Funkfernbedienung', 'mobile': None,
                                          'otomoto': None, 'marktplaats': None},
               'electric_windows': {'autoscout24': 'Elektr. Fensterheber', 'mobile': 'Elektr. Fensterheber',
                                    'otomoto': None, 'marktplaats': 'Elektrische ramen'},
               'electric_mirrors': {'autoscout24': 'Elektrische Seitenspiegel', 'mobile': 'Elektr. Seitenspiegel',
                                    'otomoto': None, 'marktplaats': 'Elektrische buitenspiegels'},
               'electric_folding_mirrors': {'autoscout24': 'AuÃŸenspiegel elektr. anklappbar',
                                            'mobile': 'Elektr. Seitenspiegel anklappbar',
                                            'otomoto': 'door_mirrors_electrically_foldable', 'marktplaats': None},
               'auto_dimming_mirror': {'autoscout24': 'Innenspiegel automatisch abblendend',
                                       'mobile': 'Innenspiegel autom. abblendend', 'otomoto': None,
                                       'marktplaats': None},
               'leather_steering_wheel': {'autoscout24': 'Lederlenkrad', 'mobile': 'Lederlenkrad',
                                          'otomoto': 'leather_steering_wheel', 'marktplaats': None},
               'heated_steering_wheel': {'autoscout24': 'Beheizbares Lenkrad', 'mobile': 'Beheizbares Lenkrad',
                                         'otomoto': 'steering_wheel_heated', 'marktplaats': 'Stuurwielverwarming'},
               'multifunction_steering_wheel': {'autoscout24': 'Multifunktionslenkrad',
                                                'mobile': 'Multifunktionslenkrad',
                                                'otomoto': 'steering_wheel_with_radio_operation', 'marktplaats': None},
               'cruise_control': {'autoscout24': 'Tempomat', 'mobile': 'Tempomat', 'otomoto': None,
                                  'marktplaats': 'Cruise Control'},
               'cruisecontrol_type': {'autoscout24': None, 'mobile': None, 'otomoto': 'cruisecontrol_type',
                                      'marktplaats': None},
               'adaptive_cruise_control': {'autoscout24': 'Abstandstempomat', 'mobile': 'Abstandstempomat',
                                           'otomoto': None, 'marktplaats': 'Adaptive Cruise Control'},
               'speed_limiter': {'autoscout24': 'Geschwindigkeits-begrenzungsanlage',
                                 'mobile': 'Geschwindigkeitsbegrenzer', 'otomoto': 'speed_limiter',
                                 'marktplaats': None},
               'start_stop_system': {'autoscout24': 'Start/Stop-Automatik', 'mobile': 'Start/Stopp-Automatik',
                                     'otomoto': 'startstop_system', 'marktplaats': 'Start-stop-systeem'},
               'parking_sensors_front': {'autoscout24': 'Einparkhilfe Sensoren vorne', 'mobile': None,
                                         'otomoto': 'park_distance_control_front', 'marktplaats': None},
               'parking_sensors_rear': {'autoscout24': 'Einparkhilfe Sensoren hinten', 'mobile': None,
                                        'otomoto': 'park_distance_control_rear', 'marktplaats': 'Parkeersensor'},
               'parking_assist': {'autoscout24': 'Einparkhilfe', 'mobile': None, 'otomoto': 'park_assistant',
                                  'marktplaats': 'Parkeerassistent'},
               'park_assist_mobile': {'autoscout24': None, 'mobile': 'parkAssists', 'otomoto': None,
                                      'marktplaats': None},
               'parking_camera': {'autoscout24': 'Einparkhilfe Kamera', 'mobile': None, 'otomoto': '360_view_camera',
                                  'marktplaats': 'Parkeercamera'},
               'exit_assist': {'autoscout24': None, 'mobile': 'Ausparkassistent', 'otomoto': None, 'marktplaats': None},
               'electronic_parking_brake': {'autoscout24': 'Elektronische Parkbremse', 'mobile': None,
                                            'otomoto': 'electric_parking_brake', 'marktplaats': None},
               'air_conditioning': {'autoscout24': 'Klimaanlage', 'mobile': None, 'otomoto': None,
                                    'marktplaats': 'Airconditioning'},
               'climate_control': {'autoscout24': 'Klimaautomatik', 'mobile': None,
                                   'otomoto': 'automatic_heating_control', 'marktplaats': 'Climate control'},
               'climate_control_2zone': {'autoscout24': '2-Zonen-Klimaautomatik', 'mobile': None, 'otomoto': None,
                                         'marktplaats': None},
               'climate_control_3zone': {'autoscout24': '3-Zonen-Klimaautomatik', 'mobile': '3-Zonen-Klimaautomatik',
                                         'otomoto': None, 'marktplaats': None},
               'climate_control_4zone': {'autoscout24': '4-Zonen-Klimaautomatik', 'mobile': '4-Zonen-Klimaautomatik',
                                         'otomoto': None, 'marktplaats': None},
               'heated_seats': {'autoscout24': 'Sitzheizung', 'mobile': 'Sitzheizung', 'otomoto': 'heated_seat_driver',
                                'marktplaats': 'Stoelverwarming'},
               'heated_rear_seats': {'autoscout24': 'Sitzheizung hinten', 'mobile': 'Sitzheizung hinten',
                                     'otomoto': 'rear_seat_heating', 'marktplaats': None},
               'massage_seats': {'autoscout24': 'Massagesitze', 'mobile': 'Massagesitze', 'otomoto': None,
                                 'marktplaats': 'Stoelmassage'},
               'electric_seats': {'autoscout24': 'Elektrische Sitze', 'mobile': 'Elektr. Sitzeinstellung',
                                  'otomoto': 'driver_seat_electrically_adjustable',
                                  'marktplaats': 'Elektrische stoelverstelling'},
               'electric_seats_memory': {'autoscout24': 'Elektr. Sitzeinstellung mit Memory-Funktion',
                                         'mobile': 'Elektr. Sitzeinstellung mit Memory-Funktion',
                                         'otomoto': 'memory_seat', 'marktplaats': None},
               'sport_seats': {'autoscout24': 'Sportsitze', 'mobile': 'Sportsitze', 'otomoto': 'sport_seats_front',
                               'marktplaats': 'Sportstoelen'},
               'armrest': {'autoscout24': 'Armlehne', 'mobile': 'Armlehne', 'otomoto': 'armrest_rear',
                           'marktplaats': None},
               'foldable_passenger_seat': {'autoscout24': 'Umklappbarer Beifahrersitz',
                                           'mobile': 'Umklappbarer Beifahrersitz', 'otomoto': None,
                                           'marktplaats': None},
               'auxiliary_heating': {'autoscout24': 'Standheizung', 'mobile': 'Standheizung',
                                     'otomoto': 'independent_vehicle_heater', 'marktplaats': None},
               'heated_windshield': {'autoscout24': 'Beheizbare Frontscheibe', 'mobile': 'Beheizbare Frontscheibe',
                                     'otomoto': 'windscreen_heating', 'marktplaats': None},
               'fog_lights': {'autoscout24': 'Nebelscheinwerfer', 'mobile': 'Nebelscheinwerfer',
                              'otomoto': 'led_fog_lamps', 'marktplaats': 'Mistlampen'},
               'xenon_lights': {'autoscout24': 'Xenonscheinwerfer', 'mobile': 'Xenonscheinwerfer', 'otomoto': None,
                                'marktplaats': 'Xenon verlichting'},
               'bi_xenon_lights': {'autoscout24': 'Bi-Xenon Scheinwerfer', 'mobile': 'Bi-Xenon Scheinwerfer',
                                   'otomoto': None, 'marktplaats': None},
               'led_headlights': {'autoscout24': 'LED-Scheinwerfer', 'mobile': 'LED-Scheinwerfer', 'otomoto': None,
                                  'marktplaats': 'LED verlichting'},
               'full_led_headlights': {'autoscout24': 'Voll-LED Scheinwerfer', 'mobile': None, 'otomoto': None,
                                       'marktplaats': None},
               'led_daytime_running_lights': {'autoscout24': 'LED-Tagfahrlicht', 'mobile': 'LED-Tagfahrlicht',
                                              'otomoto': 'led_daytime_running_lights', 'marktplaats': None},
               'daytime_running_lights': {'autoscout24': 'Tagfahrlicht', 'mobile': 'Tagfahrlicht',
                                          'otomoto': 'daytime_running_lights', 'marktplaats': None},
               'adaptive_headlights': {'autoscout24': 'Kurvenlicht', 'mobile': 'Adaptives Kurvenlicht',
                                       'otomoto': 'adaptive_light', 'marktplaats': 'Adaptieve lichten'},
               'curve_light': {'autoscout24': None, 'mobile': 'Kurvenlicht', 'otomoto': 'cornering_headlights',
                               'marktplaats': 'Bochtverlichting'},
               'high_beam_assist': {'autoscout24': 'Fernlichtassistent', 'mobile': 'Fernlichtassistent',
                                    'otomoto': 'automated_high_beam_assist', 'marktplaats': None},
               'glare_free_high_beam': {'autoscout24': 'Blendfreies Fernlicht', 'mobile': 'Blendfreies Fernlicht',
                                        'otomoto': None, 'marktplaats': None},
               'laser_light': {'autoscout24': 'Laserlicht', 'mobile': 'Laserlicht', 'otomoto': None,
                               'marktplaats': None},
               'light_sensor': {'autoscout24': 'Lichtsensor', 'mobile': 'Lichtsensor', 'otomoto': None,
                                'marktplaats': 'Lichtsensor'},
               'rain_sensor': {'autoscout24': 'Regensensor', 'mobile': 'Regensensor', 'otomoto': 'rain_sensor',
                               'marktplaats': 'Regensensor'},
               'ambient_lighting': {'autoscout24': 'Ambientebeleuchtung', 'mobile': 'Ambiente-Beleuchtung',
                                    'otomoto': 'led_interior_lighting', 'marktplaats': None},
               'headlight_washer': {'autoscout24': 'Scheinwerferreinigung', 'mobile': 'Scheinwerferreinigung',
                                    'otomoto': 'headlamp_wash', 'marktplaats': None},
               'alloy_wheels': {'autoscout24': 'Alufelgen', 'mobile': 'Leichtmetallfelgen', 'otomoto': None,
                                'marktplaats': 'Lichtmetalen velgen'},
               'alloy_wheels_type': {'autoscout24': None, 'mobile': None, 'otomoto': 'alloy_wheels_type',
                                     'marktplaats': None},
               'steel_wheels': {'autoscout24': 'Stahlfelgen', 'mobile': 'Stahlfelgen', 'otomoto': None,
                                'marktplaats': None},
               'sunroof': {'autoscout24': 'Schiebedach', 'mobile': 'Schiebedach', 'otomoto': None,
                           'marktplaats': 'Open dak'},
               'sunroof_type': {'autoscout24': None, 'mobile': None, 'otomoto': 'sunroof', 'marktplaats': None},
               'panoramic_roof': {'autoscout24': 'Panoramadach', 'mobile': 'Panorama-Dach', 'otomoto': None,
                                  'marktplaats': 'Panoramadak'},
               'folding_roof': {'autoscout24': 'Faltdach', 'mobile': 'Faltdach', 'otomoto': None, 'marktplaats': None},
               'roof_rack': {'autoscout24': 'Dachreling', 'mobile': 'Dachreling', 'otomoto': None,
                             'marktplaats': 'Dakrails'},
               'tinted_windows': {'autoscout24': 'Getönte Scheiben', 'mobile': 'Abgedunkelte Scheiben',
                                  'otomoto': 'tinted_rear_windows', 'marktplaats': None},
               'electric_tailgate': {'autoscout24': 'Elektrische Heckklappe', 'mobile': 'Elektr. Heckklappe',
                                     'otomoto': None, 'marktplaats': 'Elektrische achterklep'},
               'air_suspension': {'autoscout24': 'Luftfederung', 'mobile': 'Luftfederung', 'otomoto': 'air_suspension',
                                  'marktplaats': None},
               'sport_suspension': {'autoscout24': 'Sportfahrwerk', 'mobile': 'Sportfahrwerk',
                                    'otomoto': 'sport_suspension', 'marktplaats': None},
               'sport_package': {'autoscout24': 'Sportpaket', 'mobile': 'Sportpaket', 'otomoto': None,
                                 'marktplaats': 'Sportpakket'},
               'winter_package': {'autoscout24': 'Winterpaket', 'mobile': 'Winterpaket', 'otomoto': None,
                                  'marktplaats': None},
               'spoiler': {'autoscout24': 'Spoiler', 'mobile': 'Spoiler', 'otomoto': None, 'marktplaats': None},
               'ski_bag': {'autoscout24': 'Skisack', 'mobile': 'Skisack', 'otomoto': None, 'marktplaats': None},
               'tuning': {'autoscout24': 'Tuning', 'mobile': None, 'otomoto': 'tuning', 'marktplaats': None},
               'radio': {'autoscout24': 'Radio', 'mobile': 'Tuner/Radio', 'otomoto': 'radio', 'marktplaats': 'Radio'},
               'cd_player': {'autoscout24': 'CD', 'mobile': 'CD-Spieler', 'otomoto': None, 'marktplaats': None},
               'multi_cd_changer': {'autoscout24': 'Multi-CD-Wechsler', 'mobile': 'Multi-CD-Wechsler', 'otomoto': None,
                                    'marktplaats': None},
               'mp3': {'autoscout24': 'MP3', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'dab_radio': {'autoscout24': 'DAB-Radio', 'mobile': 'Radio DAB', 'otomoto': None, 'marktplaats': None},
               'navigation_system': {'autoscout24': 'Navigationssystem', 'mobile': 'Navigationssystem',
                                     'otomoto': 'navigation_system', 'marktplaats': 'Navigatiesysteem'},
               'navigation_preparation': {'autoscout24': 'Navigationsvorbereitung', 'mobile': 'Navigationsvorbereitung',
                                          'otomoto': None, 'marktplaats': None},
               'touchscreen': {'autoscout24': 'Touchscreen', 'mobile': 'Touchscreen', 'otomoto': 'touchscreen_monitor',
                               'marktplaats': None},
               'voice_control': {'autoscout24': 'Sprachsteuerung', 'mobile': 'Sprachsteuerung',
                                 'otomoto': 'voice_control_for_vehicle_functions', 'marktplaats': 'Spraakbediening'},
               'bluetooth': {'autoscout24': 'Bluetooth', 'mobile': 'Bluetooth', 'otomoto': 'bluetooth_interface',
                             'marktplaats': 'Bluetooth'},
               'handsfree': {'autoscout24': 'Freisprecheinrichtung', 'mobile': 'Freisprecheinrichtung',
                             'otomoto': 'hands_free_system', 'marktplaats': None},
               'usb': {'autoscout24': 'USB', 'mobile': 'USB', 'otomoto': 'usb_in', 'marktplaats': 'USB'},
               'apple_carplay': {'autoscout24': 'Apple CarPlay', 'mobile': 'Apple CarPlay', 'otomoto': 'apple_carplay',
                                 'marktplaats': 'Apple Carplay'},
               'android_auto': {'autoscout24': 'Android Auto', 'mobile': 'Android Auto', 'otomoto': 'android_auto',
                                'marktplaats': 'Android Auto'},
               'wifi_hotspot': {'autoscout24': 'W-Lan / Wifi Hotspot', 'mobile': 'WLAN / Wifi Hotspot',
                                'otomoto': 'internet_access', 'marktplaats': None},
               'music_streaming': {'autoscout24': 'Musikstreaming integriert', 'mobile': 'Musikstreaming integriert',
                                   'otomoto': None, 'marktplaats': None},
               'sound_system': {'autoscout24': 'Soundsystem', 'mobile': 'Soundsystem', 'otomoto': 'soundsystem',
                                'marktplaats': None},
               'onboard_computer': {'autoscout24': 'Bordcomputer', 'mobile': 'Bordcomputer', 'otomoto': None,
                                    'marktplaats': 'Boordcomputer'},
               'digital_cockpit': {'autoscout24': 'Volldigitales Kombiinstrument',
                                   'mobile': 'Volldigitales Kombiinstrument', 'otomoto': 'head_up_display',
                                   'marktplaats': None},
               'tv': {'autoscout24': 'TV', 'mobile': 'TV', 'otomoto': None, 'marktplaats': None},
               'all_season_tires': {'autoscout24': 'Allwetterreifen', 'mobile': 'Allwetterreifen', 'otomoto': None,
                                    'marktplaats': None},
               'summer_tires': {'autoscout24': 'Sommerreifen', 'mobile': 'Sommerreifen', 'otomoto': None,
                                'marktplaats': None},
               'winter_tires': {'autoscout24': 'Winterreifen', 'mobile': 'Winterreifen', 'otomoto': None,
                                'marktplaats': None},
               'spare_wheel': {'autoscout24': 'Reserverad', 'mobile': 'Reserverad', 'otomoto': None,
                               'marktplaats': None},
               'emergency_wheel': {'autoscout24': 'Notrad', 'mobile': 'Notrad', 'otomoto': None, 'marktplaats': None},
               'tire_repair_kit': {'autoscout24': 'Pannenkit', 'mobile': 'Pannenkit', 'otomoto': None,
                                   'marktplaats': None},
               'catalytic_converter': {'autoscout24': 'Katalysator', 'mobile': None, 'otomoto': None,
                                       'marktplaats': None},
               'e10_compatible': {'autoscout24': 'E10-geeignet', 'mobile': None, 'otomoto': None, 'marktplaats': None},
               'all_wheel_drive': {'autoscout24': 'Allrad', 'mobile': 'Allradantrieb', 'otomoto': None,
                                   'marktplaats': '4x4'},
               'front_wheel_drive': {'autoscout24': None, 'mobile': 'Frontantrieb', 'otomoto': None,
                                     'marktplaats': None},
               'rear_wheel_drive': {'autoscout24': None, 'mobile': 'Heckantrieb', 'otomoto': None, 'marktplaats': None},
               'warranty': {'autoscout24': 'Garantie', 'mobile': 'Garantie', 'otomoto': None, 'marktplaats': None},
               'export': {'autoscout24': None, 'mobile': 'export', 'otomoto': None, 'marktplaats': None},
               'right_hand_drive': {'autoscout24': 'Rechtslenker', 'mobile': 'Rechtslenker', 'otomoto': 'rhd',
                                    'marktplaats': None},
               'taxi': {'autoscout24': None, 'mobile': 'Taxi', 'otomoto': None, 'marktplaats': None},
               'disabled_accessible': {'autoscout24': 'Behindertengerecht', 'mobile': 'Behindertengerecht',
                                       'otomoto': None, 'marktplaats': 'Aangepast voor mindervaliden'},
               'smoker_package': {'autoscout24': 'Raucherpaket', 'mobile': 'Raucherpaket', 'otomoto': None,
                                  'marktplaats': None},
               'leather_interior': {'autoscout24': 'Lederausstattung', 'mobile': None, 'otomoto': None,
                                    'marktplaats': 'Lederen bekleding'},
               'paddle_shifters': {'autoscout24': 'Schaltwippen', 'mobile': 'Schaltwippen',
                                   'otomoto': 'steering_wheel_with_gear_switches', 'marktplaats': None},
               'energy_recovery_system': {'autoscout24': None, 'mobile': None, 'otomoto': 'energy_recovery_system',
                                          'marktplaats': None},
               'rear_transversal_curtain_airbag': {'autoscout24': None, 'mobile': None,
                                                   'otomoto': 'rear_transversal_curtain_airbag', 'marktplaats': None},
               'leasing_concession': {'autoscout24': None, 'mobile': None, 'otomoto': 'leasing_concession',
                                      'marktplaats': None},
               'lumbar_adjust_passenger_electric': {'autoscout24': None, 'mobile': None,
                                                    'otomoto': 'lumbar_adjust_passenger_electric', 'marktplaats': None},
               'pause_recommendation_warning': {'autoscout24': None, 'mobile': None,
                                                'otomoto': 'pause_recommendation_warning', 'marktplaats': None},
               'top_electrically_operated': {'autoscout24': None, 'mobile': None,
                                             'otomoto': 'top_electrically_operated', 'marktplaats': None},
               'vat': {'autoscout24': None, 'mobile': None, 'otomoto': 'vat', 'marktplaats': None},
               'acoustic_vehicle_alerting_system': {'autoscout24': None, 'mobile': None,
                                                    'otomoto': 'acoustic_vehicle_alerting_system', 'marktplaats': None},
               'has_vin': {'autoscout24': None, 'mobile': None, 'otomoto': 'has_vin', 'marktplaats': None},
               'property_updatedAt': {'autoscout24': None, 'mobile': None, 'otomoto': 'property_updatedAt',
                                      'marktplaats': None},
               'convertible_top_type': {'autoscout24': None, 'mobile': None, 'otomoto': 'convertible_top_type',
                                        'marktplaats': None},
               'electronic_controlled_suspension': {'autoscout24': None, 'mobile': None,
                                                    'otomoto': 'electronic_controlled_suspension', 'marktplaats': None},
               'residual_value': {'autoscout24': None, 'mobile': None, 'otomoto': 'residual_value',
                                  'marktplaats': None},
               'tyre_type': {'autoscout24': None, 'mobile': None, 'otomoto': 'tyre_type', 'marktplaats': None},
               'maker_warranty_valid_until_km': {'autoscout24': None, 'mobile': None,
                                                 'otomoto': 'maker_warranty_valid_until_km', 'marktplaats': None},
               'battery_type': {'autoscout24': None, 'mobile': None, 'otomoto': 'battery_type', 'marktplaats': None},
               'front_airbags_for_rear_seats': {'autoscout24': None, 'mobile': None,
                                                'otomoto': 'front_airbags_for_rear_seats', 'marktplaats': None},
               'city_emergency_brake_assist': {'autoscout24': None, 'mobile': None,
                                               'otomoto': 'city_emergency_brake_assist', 'marktplaats': None},
               'cant_see_my_version': {'autoscout24': None, 'mobile': None, 'otomoto': 'cant_see_my_version',
                                       'marktplaats': None},
               'vehicle_charging_cable': {'autoscout24': None, 'mobile': None, 'otomoto': 'vehicle_charging_cable',
                                          'marktplaats': None},
               'vendors_warranty_valid_until_date': {'autoscout24': None, 'mobile': None,
                                                     'otomoto': 'vendors_warranty_valid_until_date',
                                                     'marktplaats': None},
               'intersection_assist': {'autoscout24': None, 'mobile': None, 'otomoto': 'intersection_assist',
                                       'marktplaats': None},
               'air_condition_rear': {'autoscout24': None, 'mobile': None, 'otomoto': 'air_condition_rear',
                                      'marktplaats': None},
               'originalCreatedAt': {'autoscout24': None, 'mobile': None, 'otomoto': 'originalCreatedAt',
                                     'marktplaats': None},
               'adjustable_suspension': {'autoscout24': None, 'mobile': None, 'otomoto': 'adjustable_suspension',
                                         'marktplaats': None},
               'driver_conditioning_monitoring': {'autoscout24': None, 'mobile': None,
                                                  'otomoto': 'driver_conditioning_monitoring',
                                                  'marktplaats': 'Vermoeidheidsdetectie'},
               'maker_warranty_valid_until_date': {'autoscout24': None, 'mobile': None,
                                                   'otomoto': 'maker_warranty_valid_until_date', 'marktplaats': None},
               'pre_crash_sound_system': {'autoscout24': None, 'mobile': None, 'otomoto': 'pre_crash_sound_system',
                                          'marktplaats': None},
               'windscreenwiper_other': {'autoscout24': None, 'mobile': None, 'otomoto': 'windscreenwiper_other',
                                         'marktplaats': None},
               'electric_power_peak': {'autoscout24': None, 'mobile': None, 'otomoto': 'electric_power_peak',
                                       'marktplaats': None},
               'rear_pre_crash_system': {'autoscout24': None, 'mobile': None, 'otomoto': 'rear_pre_crash_system',
                                         'marktplaats': None},
               'vat_discount': {'autoscout24': None, 'mobile': None, 'otomoto': 'vat_discount', 'marktplaats': None},
               'max_charging_power': {'autoscout24': None, 'mobile': None, 'otomoto': 'max_charging_power',
                                      'marktplaats': None},
               'power_windows_rear': {'autoscout24': None, 'mobile': None, 'otomoto': 'power_windows_rear',
                                      'marktplaats': None},
               'quick_charging_function': {'autoscout24': None, 'mobile': None, 'otomoto': 'quick_charging_function',
                                           'marktplaats': None},
               'brake_energy_recovery': {'autoscout24': None, 'mobile': None, 'otomoto': 'brake_energy_recovery',
                                         'marktplaats': None},
               'historical_vehicle': {'autoscout24': None, 'mobile': None, 'otomoto': 'historical_vehicle',
                                      'marktplaats': None},
               'charging_connector_type': {'autoscout24': None, 'mobile': None, 'otomoto': 'charging_connector_type',
                                           'marktplaats': None},
               'side_pre_crash_system': {'autoscout24': None, 'mobile': None, 'otomoto': 'side_pre_crash_system',
                                         'marktplaats': None},
               'approval_for_goods': {'autoscout24': None, 'mobile': None, 'otomoto': 'approval_for_goods',
                                      'marktplaats': None},
               'led_rear_lights': {'autoscout24': None, 'mobile': None, 'otomoto': 'led_rear_lights',
                                   'marktplaats': None},
               'active_driver_conditioning_monitoring': {'autoscout24': None, 'mobile': None,
                                                         'otomoto': 'active_driver_conditioning_monitoring',
                                                         'marktplaats': None},
               'is_imported_car': {'autoscout24': None, 'mobile': None, 'otomoto': 'is_imported_car',
                                   'marktplaats': 'isImported'},
               'system_performance_of_hybrid_driveline_in_hp': {'autoscout24': None, 'mobile': None,
                                                                'otomoto': 'system_performance_of_hybrid_driveline_in_hp',
                                                                'marktplaats': None},
               'runflat_tyres': {'autoscout24': None, 'mobile': None, 'otomoto': 'runflat_tyres', 'marktplaats': None},
               'charging_time_home': {'autoscout24': None, 'mobile': None, 'otomoto': 'charging_time_home',
                                      'marktplaats': None},
               'rear_cross_traffic_alert': {'autoscout24': None, 'mobile': None, 'otomoto': 'rear_cross_traffic_alert',
                                            'marktplaats': None},
               'top_remote_controlled': {'autoscout24': None, 'mobile': None, 'otomoto': 'top_remote_controlled',
                                         'marktplaats': None},
               'knee_airbag_driver': {'autoscout24': None, 'mobile': None, 'otomoto': 'knee_airbag_driver',
                                      'marktplaats': None},
               'rear_seat_with_massage': {'autoscout24': None, 'mobile': None, 'otomoto': 'rear_seat_with_massage',
                                          'marktplaats': None},
               'comfort_suspension': {'autoscout24': None, 'mobile': None, 'otomoto': 'comfort_suspension',
                                      'marktplaats': None},
               'financial_option': {'autoscout24': None, 'mobile': None, 'otomoto': 'financial_option',
                                    'marktplaats': None},
               'collision_warning_system': {'autoscout24': None, 'mobile': None, 'otomoto': 'collision_warning_system',
                                            'marktplaats': None},
               'pre_crash_system': {'autoscout24': None, 'mobile': None, 'otomoto': 'pre_crash_system',
                                    'marktplaats': None},
               'selectable_central_differential_characteristics': {'autoscout24': None, 'mobile': None,
                                                                   'otomoto': 'selectable_central_differential_characteristics',
                                                                   'marktplaats': None},
               'keyless_entry': {'autoscout24': None, 'mobile': None, 'otomoto': 'keyless_entry',
                                 'marktplaats': 'Keyless entry'},
               'charging_current_type': {'autoscout24': None, 'mobile': None, 'otomoto': 'charging_current_type',
                                         'marktplaats': None},
               'automatic_dimlight_activation': {'autoscout24': None, 'mobile': None,
                                                 'otomoto': 'automatic_dimlight_activation', 'marktplaats': None},
               'knee_airbag_passenger': {'autoscout24': None, 'mobile': None, 'otomoto': 'knee_airbag_passenger',
                                         'marktplaats': None},
               'front_seat_with_massage': {'autoscout24': None, 'mobile': None, 'otomoto': 'front_seat_with_massage',
                                           'marktplaats': None},
               'pedestrian_emergency_brake_assist': {'autoscout24': None, 'mobile': None,
                                                     'otomoto': 'pedestrian_emergency_brake_assist',
                                                     'marktplaats': None},
               'ceramic_composite_brakes': {'autoscout24': None, 'mobile': None, 'otomoto': 'ceramic_composite_brakes',
                                            'marktplaats': None},
               'limited_slip_differential_in_general': {'autoscout24': None, 'mobile': None,
                                                        'otomoto': 'limited_slip_differential_in_general',
                                                        'marktplaats': None},
               'ventilated_rear_seat': {'autoscout24': None, 'mobile': None, 'otomoto': 'ventilated_rear_seat',
                                        'marktplaats': None},
               'lease_url': {'autoscout24': None, 'mobile': None, 'otomoto': 'lease_url', 'marktplaats': None},
               'autorenew': {'autoscout24': None, 'mobile': None, 'otomoto': 'autorenew', 'marktplaats': None},
               'number_engines': {'autoscout24': None, 'mobile': None, 'otomoto': 'number_engines',
                                  'marktplaats': None},
               'leather_gearshifterswitch': {'autoscout24': None, 'mobile': None,
                                             'otomoto': 'leather_gearshifterswitch', 'marktplaats': None},
               'remaining_payments': {'autoscout24': None, 'mobile': None, 'otomoto': 'remaining_payments',
                                      'marktplaats': None},
               'active_lane_change_assistant': {'autoscout24': None, 'mobile': None,
                                                'otomoto': 'active_lane_change_assistant', 'marktplaats': None},
               'distribution_of_braking_force_electronically': {'autoscout24': None, 'mobile': None,
                                                                'otomoto': 'distribution_of_braking_force_electronically',
                                                                'marktplaats': None},
               'vehicle_title': {'autoscout24': None, 'mobile': None, 'otomoto': 'vehicle_title', 'marktplaats': None},
               'follow_me_home': {'autoscout24': None, 'mobile': None, 'otomoto': 'follow_me_home',
                                  'marktplaats': None},
               'power_assisted_brakes': {'autoscout24': None, 'mobile': None, 'otomoto': 'power_assisted_brakes',
                                         'marktplaats': None},
               'curve_trace_assistant': {'autoscout24': None, 'mobile': None, 'otomoto': 'curve_trace_assistant',
                                         'marktplaats': None},
               'headlight_lamp_type': {'autoscout24': None, 'mobile': None, 'otomoto': 'headlight_lamp_type',
                                       'marktplaats': None},
               'basic_autonomous_driving': {'autoscout24': None, 'mobile': None, 'otomoto': 'basic_autonomous_driving',
                                            'marktplaats': 'Autonomous Driving'},
               'hill_descent_control': {'autoscout24': None, 'mobile': None, 'otomoto': 'hill_descent_control',
                                        'marktplaats': None},
               'door_mirrors_heated': {'autoscout24': None, 'mobile': None, 'otomoto': 'door_mirrors_heated',
                                       'marktplaats': None},
               'power_windows_front': {'autoscout24': None, 'mobile': None, 'otomoto': 'power_windows_front',
                                       'marktplaats': None},
               'sunblind_type': {'autoscout24': None, 'mobile': None, 'otomoto': 'sunblind_type', 'marktplaats': None},
               'sports_steering_wheel': {'autoscout24': None, 'mobile': None, 'otomoto': 'sports_steering_wheel',
                                         'marktplaats': None},
               'charging_time_80': {'autoscout24': None, 'mobile': None, 'otomoto': 'charging_time_80',
                                    'marktplaats': None},
               'keyless_engine_start': {'autoscout24': None, 'mobile': None, 'otomoto': 'keyless_engine_start',
                                        'marktplaats': None},
               'digital_key': {'autoscout24': None, 'mobile': None, 'otomoto': 'digital_key', 'marktplaats': None},
               'monthly_payment': {'autoscout24': None, 'mobile': None, 'otomoto': 'monthly_payment',
                                   'marktplaats': None},
               'hydro_pneumatic_suspension': {'autoscout24': None, 'mobile': None,
                                              'otomoto': 'hydro_pneumatic_suspension', 'marktplaats': None},
               'door_mirror_camera': {'autoscout24': None, 'mobile': None, 'otomoto': 'door_mirror_camera',
                                      'marktplaats': None},
               'door_mirror_electrically_adjustable_in_general': {'autoscout24': None, 'mobile': None,
                                                                  'otomoto': 'door_mirror_electrically_adjustable_in_general',
                                                                  'marktplaats': None},
               'steering_wheel_electrically_adjustable': {'autoscout24': None, 'mobile': None,
                                                          'otomoto': 'steering_wheel_electrically_adjustable',
                                                          'marktplaats': None},
               'catalog_urn': {'autoscout24': None, 'mobile': None, 'otomoto': 'catalog_urn', 'marktplaats': None},
               'battery_condition': {'autoscout24': None, 'mobile': None, 'otomoto': 'battery_condition',
                                     'marktplaats': None},
               'central_airbag_driver_and_passenger': {'autoscout24': None, 'mobile': None,
                                                       'otomoto': 'central_airbag_driver_and_passenger',
                                                       'marktplaats': None},
               'traffic_jam_assist': {'autoscout24': None, 'mobile': None, 'otomoto': 'traffic_jam_assist',
                                      'marktplaats': None},
               'property_created_at': {'autoscout24': None, 'mobile': None, 'otomoto': 'property_created_at',
                                       'marktplaats': None},
               'deactivation_reason_id': {'autoscout24': None, 'mobile': None, 'otomoto': 'deactivation_reason_id',
                                          'marktplaats': None},
               'number_batteries': {'autoscout24': None, 'mobile': None, 'otomoto': 'number_batteries',
                                    'marktplaats': None},
               'video': {'autoscout24': None, 'mobile': None, 'otomoto': 'video', 'marktplaats': None},
               'seat_belt_airbag_rear': {'autoscout24': None, 'mobile': None, 'otomoto': 'seat_belt_airbag_rear',
                                         'marktplaats': None},
               'down_payment': {'autoscout24': None, 'mobile': None, 'otomoto': 'down_payment', 'marktplaats': None},
               'keyless_go': {'autoscout24': None, 'mobile': None, 'otomoto': 'keyless_go', 'marktplaats': None},
               'roll_over_protection_system': {'autoscout24': None, 'mobile': None,
                                               'otomoto': 'roll_over_protection_system', 'marktplaats': None},
               'tires': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'tires'},
               'newCarPrice': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'newCarPrice'},
               'rearBrakes': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'rearBrakes'},
               'camera_360': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': '360° camera'},
               'perKilometer': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'perKilometer'},
               'Metallic_lak': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'Metallic lak'},
               'powerWheelDriver': {'autoscout24': None, 'mobile': None, 'otomoto': None,
                                    'marktplaats': 'powerWheelDriver'},
               'forward_camera': {'autoscout24': None, 'mobile': None, 'otomoto': None,
                                  'marktplaats': 'Vooruitrijcamera'},
               'hasNapStatus': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'hasNapStatus'},
               'hybridType': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'hybridType'},
               'firstRecordInNl': {'autoscout24': None, 'mobile': None, 'otomoto': None,
                                   'marktplaats': 'firstRecordInNl'},
               'isTurbo': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'isTurbo'},
               'assurancesCars': {'autoscout24': None, 'mobile': None, 'otomoto': None,
                                  'marktplaats': 'assurancesCars'},
               'ownerSince': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'ownerSince'},
               'Head_up_Display': {'autoscout24': None, 'mobile': None, 'otomoto': None,
                                   'marktplaats': 'Head-up Display'},
               'perYear': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'perYear'},
               'batteryFastChargeTime': {'autoscout24': None, 'mobile': None, 'otomoto': None,
                                         'marktplaats': 'batteryFastChargeTime'},
               'acceleration': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'acceleration'},
               'fuelPerMonth': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'fuelPerMonth'},
               'energyLabel': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'energyLabel'},
               'carCapacityBootMinMax': {'autoscout24': None, 'mobile': None, 'otomoto': None,
                                         'marktplaats': 'carCapacityBootMinMax'},
               'torque': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'torque'},
               'totalCostPerMonth': {'autoscout24': None, 'mobile': None, 'otomoto': None,
                                     'marktplaats': 'totalCostPerMonth'},
               'repairAndMileage': {'autoscout24': None, 'mobile': None, 'otomoto': None,
                                    'marktplaats': 'repairAndMileage'},
               'euronormBE': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'euronormBE'},
               'topSpeed': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'topSpeed'},
               'frontBrakes': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'frontBrakes'},
               'heated_mirror': {'autoscout24': None, 'mobile': None, 'otomoto': None,
                                 'marktplaats': 'Verwarmde buitenspiegels'},
               'enriched': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'enriched'},
               'reversing_camera': {'autoscout24': None, 'mobile': None, 'otomoto': None,
                                    'marktplaats': 'Achteruitrijcamera'},
               'lastOwnerType': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'lastOwnerType'},
               'dateApk': {'autoscout24': None, 'mobile': None, 'otomoto': None, 'marktplaats': 'dateApk'}}


def convert_vehicle_data(data, source='autoscout24'):
    """
    Convert vehicle data from source format to unified format

    Args:
        data (dict): Source vehicle data
        source (str): Source name ('autoscout24' or 'mobile')

    Returns:
        dict: Unified vehicle data
    """
    if source not in ['autoscout24', 'mobile', 'otomoto', 'marktplaats']:
        raise ValueError("Source must be 'autoscout24' or 'mobile' or 'otomoto'")

    unified_data = {}
    unified_data['data_source'] = source  # Track origin

    for unified_key, source_keys in KEY_MAPPING.items():
        source_key = source_keys.get(source)

        if source_key and source_key in data:
            value = data[source_key]
            # Only add non-None values
            if value is not None and value != '':
                unified_data[unified_key] = value
            else:
                unified_data[unified_key] = None
        else:
            unified_data[unified_key] = None

    return unified_data
